domains:
    urn:ngsi-ld:Domain:ucy:01: 
        country: CYPRUS
        RES:
            - model_name: inverter1
              location: 
                  lat: 51.9194
                  lon: 19.1451
            - model_name: inverter2
              location: 
                  lat: 51.9194
                  lon: 19.1451
            - model_name: inverter3
              location: 
                  lat: 51.9194
                  lon: 19.1451
    # CloudFerro:
    #     country: POLAND
    #     RES:
    #         - model_name: inverter1
    #           location: 
    #               lat: 51.9194
    #               lon: 19.1451
    #         - model_name: inverter2
    #           location: 
    #               lat: 51.9194
    #               lon: 19.1451
    #         - model_name: inverter3
    #           location: 
    #               lat: 51.9194
    #               lon: 19.1451
energy-profiles:
    - infrastructure_element_id: urn:ngsi-ld:InfrastructureElement:ucypi
      energy_model_id: RPI4

authorization: "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJzaTcxSzNkUm11UFIxY2RhT2daNVFtbGpUVlR6U3JQM0cyYlZNdEVDeUVjIn0.eyJleHAiOjE4MTQxODAzOTEsImlhdCI6MTcyNzg2Njc5MSwianRpIjoiNTQ5OWEyNjgtMGI2Ni00NzY4LWI0MTUtMDc1ZWYzYTg0ZDU1IiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5jZi1tdnAtZG9tYWluLmFlcm9zLXByb2plY3QuZXUvYXV0aC9yZWFsbXMva2V5Y2xvYWNrLW9wZW5sZGFwIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImQwMTg1ZTc3LWZhNWItNDg0MS1iMmU0LTNkZDdmZTMwYjIxNCIsInR5cCI6IkJlYXJlciIsImF6cCI6IkNvbnRleHRCcm9rZXIiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMta2V5Y2xvYWNrLW9wZW5sZGFwIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkRvbWFpbiBhZG1pbmlzdHJhdG9yIiwiQ29udGV4dEJyb2tlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImNsaWVudEhvc3QiOiIxMC4xMDAuMi4xNzYiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImNsaWVudElkIjoiQ29udGV4dEJyb2tlciIsInByZWZlcnJlZF91c2VybmFtZSI6InNlcnZpY2UtYWNjb3VudC1jb250ZXh0YnJva2VyIiwiY2xpZW50QWRkcmVzcyI6IjEwLjEwMC4yLjE3NiJ9.rnH4xu5DLrEQsvNRHLlAKHBhn32reCmRTW--6GChfI8beqIAvuxJHVO31xFTFSEaWSw9rYIe-OUwch1xewVRLtJF7SirhGsJ6NOUr1NVkBRYIACFguTF-Zwnb8LwfMCEtj-Ykne61oh46Mnd1GQYecrvh_M_vFr7Azlxyn2mGe3QMdFoMEVmwhGZRCQlLYJvppUbj7OBxS-obb7tgi-5lzuuGaXvcSt5LHMhRtvsoDDYRTNRdNgxEEIerR3QWmuz3YV9Ec_f7wvvH34BJCrkyjfYezvpOraUP61eFmRtVAO1p4mSfmBQigCMZqbucmBVsOHoc3jd_959HMqiuOOOoA"