# Generated by Django 3.2.4 on 2024-07-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryEnergyMix',
            fields=[
                ('country', models.CharField(choices=[('CYPRUS', 'CYPRUS'), ('POLAND', 'POLAND')], max_length=100, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('stored_model', models.FileField(upload_to='energy_mix_models')),
            ],
        ),
        migrations.CreateModel(
            name='RESModel',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('res_type', models.CharField(choices=[('PV', 'PV'), ('WIND', 'WIND')], max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('model_type', models.CharField(choices=[('AI', 'AI'), ('NAIVE', 'NAIVE'), ('MATH', 'MATH')], max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stored_model', models.FileField(upload_to='energy_pv_models')),
            ],
        ),
    ]
