# Generated by Django 3.2.4 on 2024-10-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenAnalyzer', '0002_auto_20240726_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyProfile',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('dynamic', models.FloatField()),
                ('static', models.FloatField()),
            ],
        ),
    ]
