version: '3.3'

services:
  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: 'greenuser'
      POSTGRES_PASSWORD: 'greenpass'
      POSTGRES_DB: 'green_analyzer'
    volumes:
      - "${PWD}/data:/var/lib/postgresql/data:Z"

  web:
    build: .
    image: greenanalyzer:test
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      ENTSOE_API_KEY: '56ec3e0b-6e1d-4537-896e-d6b61556b40e'
      SECRET_KEY: 'django-insecure-eyqs-m'

volumes:
  postgres_data:
