# Generated by Django 3.2.4 on 2024-07-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryEnergyMix',
        ),
        migrations.AlterField(
            model_name='resmodel',
            name='stored_model',
            field=models.FileField(default=None, upload_to='energy_pv_models'),
        ),
    ]
